### ISSUE TITLE
Need help about robot arm simulation in UE

### ISSUE THREAD

**Issue by aiolosgs** [charan-vendra/charan-vendra#1]
Hi, I'm working on a project about robot arm simulation in UE, but I'm new to both robot arm and Unreal Engine. The problem I met now is how to import the model of my robot arm into UE. I already have a urdf file which describes the links and joints of the robot arm and some stl files for links, but I can not find any docs about how to use these resources in UE, could you please give me some advice about how to make my first step. Thanks.

**Comment by charan-vendra** [comment]
Hi @aiolosg,
I have worked on a similar project before, let me know if this helps your cause:
`https://www.youtube.com/watch?v=v4HKzkKbSkc&t=13s&pp=ygUXeGVyYmVyIHJvYm90IGFybSB1bnJlYWw%3D`
If not please contact me here:
`https://fiverr.com/charanfiverr`

Feel free to reopen the issue if needed.
